/**
 * hook-rule-gate.ts — generates the in-container PreToolUse hook-rule
 * evaluator for the bench surface (hook-rule P1 plan, Task 7). Nothing in
 * this module runs INSIDE a container itself: it produces the `eval.sh`
 * TEXT that Task 8's cmd-run.ts wiring copies in, mirroring rule-gate.ts's
 * `buildRuleGateScript`/copy-in split exactly.
 *
 * Rule embedding: every per-rule field — including the two fully-formed
 * output JSON lines (deny / additionalContext, P0-verified shapes) — is
 * built at GENERATION time in TS and embedded as sh-single-quote-escaped
 * literals (rule-gate.ts's `shQuote`). The script never JSON-escapes or
 * parses the rule table at runtime — a JSON parser written in plain bash is
 * the fragile option this module avoids (rule-gate.ts module header).
 *
 * Input extraction (frozen contract 3, DOCUMENTED LIMITATION — accepted for
 * P1, shadow-only): `tool_name` and the canonical input field (`command` /
 * `file_path`) are pulled from the stdin JSON with sed. Two known holes:
 *  1. an embedded escaped quote (\") in the value truncates the extraction
 *     at it;
 *  2. sed's greedy `.*` binds to the LAST occurrence of the key name, so a
 *     command whose own text contains e.g. `"command":"..."` can shadow the
 *     real field.
 * Both are zero-behavioral-risk while every rule is shadow-born (worst case:
 * a missed/false outcomes.log line), and MUST be revisited before any bench
 * deny arm — P3 gate item, tracked at barrier K3.
 *
 * Fail-open (spec law): the script ALWAYS exits 0 — malformed stdin, unknown
 * tool, unwritable outcomes dir, zero rules: all silent allows. A PreToolUse
 * hook only blocks via its stdout JSON, and only a deny-mode match (with
 * killSwitch off) ever emits one.
 *
 * Portability: bash 3.2 floor, same as rule-gate.ts's generated script — no
 * `set -u`/`set -e` (zero-length-array + fail-open), POSIX ERE only via
 * `[[ =~ ]]` with the pattern in a variable (the §2 birth screen guarantees
 * every exported pattern is POSIX-ERE-portable; this script never re-screens
 * — export-time enforcement, spec §3).
 *
 * F2: outcomes.log carries `<id> <mode> <epoch-seconds>` per matched rule —
 * never the input text.
 */
import { shQuote } from "./rule-gate.ts"

/** Where the evaluator script + outcomes log live inside the container.
 * Overridable via the `HOOK_RULE_GATE_DIR` env var — baked into the
 * generated script as its default, read at script-runtime from the env for
 * testability (rule-gate.ts's `RULE_GATE_DIR` precedent). */
export const HOOK_RULE_GATE_DIR = "/app/.hookrule-gate"

/** One compiled-table rule (frozen contract 2's `rules[]` entry shape) —
 * a plain structural type on purpose: this module takes the parsed table as
 * an argument and imports nothing from the store lane. */
export interface HookRuleSpec {
  id: string
  toolMatcher: string
  inputPattern: string
  feedback: string
  mode: string
}

/** The P0-verified PreToolUse deny output (PROBE.md verdict A). */
function denyJson(feedback: string): string {
  return JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: feedback,
    },
  })
}

/** The P0-verified non-blocking context output (PROBE.md verdict B) — also
 * the killSwitch demotion target for a deny match (contract 3). */
function warnJson(feedback: string): string {
  return JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      additionalContext: feedback,
    },
  })
}

/**
 * Generate the full `eval.sh` text for one PreToolUse invocation. Evaluates
 * every embedded rule whose toolMatcher equals the call's tool (match =
 * violation, contract 3), logs each match to outcomes.log, then emits the
 * severest matched rule's output — first-by-embedded-order tiebreak, which
 * is id order (the exporter stable-sorts by numeric bullet id, contract 2).
 */
export function buildHookRuleEvalScript(rules: HookRuleSpec[], killSwitch: boolean): string {
  const idsLiteral = rules.map((r) => shQuote(r.id)).join(" ")
  const toolsLiteral = rules.map((r) => shQuote(r.toolMatcher)).join(" ")
  const patternsLiteral = rules.map((r) => shQuote(r.inputPattern)).join(" ")
  const modesLiteral = rules.map((r) => shQuote(r.mode)).join(" ")
  const denyLiteral = rules.map((r) => shQuote(denyJson(r.feedback))).join(" ")
  const warnLiteral = rules.map((r) => shQuote(warnJson(r.feedback))).join(" ")

  return `#!/bin/bash
# Generated by hook-rule-gate.ts (buildHookRuleEvalScript) — do not hand-edit.
# Fail-open contract: this script must ALWAYS exit 0; only its stdout JSON
# (deny-mode match, killSwitch off) ever blocks a tool call. No 'set -u'
# (bash 3.2 zero-length arrays) and no 'set -e' (any command failure must
# fall through to the silent allow).

HOOK_RULE_GATE_DIR="\${HOOK_RULE_GATE_DIR:-${HOOK_RULE_GATE_DIR}}"
mkdir -p "$HOOK_RULE_GATE_DIR" 2>/dev/null
OUTCOMES="$HOOK_RULE_GATE_DIR/outcomes.log"
KILL_SWITCH=${killSwitch ? 1 : 0}

RULE_IDS=(${idsLiteral})
RULE_TOOLS=(${toolsLiteral})
RULE_PATTERNS=(${patternsLiteral})
RULE_MODES=(${modesLiteral})
RULE_DENY_JSON=(${denyLiteral})
RULE_WARN_JSON=(${warnLiteral})

INPUT="$(cat 2>/dev/null)"

# sed JSON extraction — module-header caveat: truncates at an embedded \\"
# and greedy .* binds to the LAST key occurrence. Accepted for P1
# (shadow-only); P3 gate item before any bench deny arm.
TOOL="$(printf '%s' "$INPUT" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)"
[ -n "$TOOL" ] || exit 0

# Canonical input field per tool (frozen contract 3).
case "$TOOL" in
  Bash)
    VALUE="$(printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)"
    ;;
  Edit|Write|Read)
    VALUE="$(printf '%s' "$INPUT" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\\([^"]*\\)".*/\\1/p' | head -1)"
    ;;
  Glob|Grep)
    # JSON-serialized tool input: everything from the tool_input value on
    # (keeps the leading '{' so ^-anchored patterns see the same text shape
    # as the dogfood evaluator's JSON.stringify; trailing outer-object bytes
    # ride along — same caveat class as above, shadow-only).
    VALUE="$(printf '%s' "$INPUT" | sed -n 's/.*"tool_input"[[:space:]]*:[[:space:]]*\\(.*\\)/\\1/p' | head -1)"
    ;;
  *)
    exit 0
    ;;
esac

BEST=-1
BEST_RANK=0
NOW="$(date +%s)"
i=0
while [ "$i" -lt "\${#RULE_IDS[@]}" ]; do
  if [ "\${RULE_TOOLS[$i]}" = "$TOOL" ]; then
    pat="\${RULE_PATTERNS[$i]}"
    if [[ "$VALUE" =~ $pat ]]; then
      # F2: id/mode/epoch only — never the input text.
      printf '%s %s %s\\n' "\${RULE_IDS[$i]}" "\${RULE_MODES[$i]}" "$NOW" 2>/dev/null >> "$OUTCOMES"
      case "\${RULE_MODES[$i]}" in
        deny) rank=3 ;;
        warn) rank=2 ;;
        *) rank=1 ;;
      esac
      # Strict > keeps the FIRST rule at the severest rank (id-order tiebreak).
      if [ "$rank" -gt "$BEST_RANK" ]; then
        BEST_RANK=$rank
        BEST=$i
      fi
    fi
  fi
  i=$((i + 1))
done

[ "$BEST" -ge 0 ] || exit 0

case "\${RULE_MODES[$BEST]}" in
  deny)
    if [ "$KILL_SWITCH" = "1" ]; then
      printf '%s\\n' "\${RULE_WARN_JSON[$BEST]}"
    else
      printf '%s\\n' "\${RULE_DENY_JSON[$BEST]}"
    fi
    ;;
  warn)
    printf '%s\\n' "\${RULE_WARN_JSON[$BEST]}"
    ;;
esac
exit 0
`
}

/** The `podman exec` argv TAIL for post-attempt outcomes readback — pairs
 * with `buildExecArgv(name, readHookRuleOutcomesArgs())` at the call site,
 * mirroring rule-gate.ts's `readRuleGateStateArgs` precedent exactly. */
export function readHookRuleOutcomesArgs(): string[] {
  return ["cat", `${HOOK_RULE_GATE_DIR}/outcomes.log`]
}
