/**
 * hook-rule-transition-candidate.test.ts — TDD for
 * src/hook-rule-transition-candidate.ts (hook-rule P3 plan, T5). Written
 * FIRST, failing (module did not exist yet).
 *
 * Contract 4: warn-only precondition, deny-cap pre-check among exportable
 * rules, playbook copy with ONLY the target mode flipped, store-convention
 * version numbering, transition provenance in meta.json. System-generated by
 * construction: never touches propose/review-gate code paths.
 */
import { afterEach, beforeEach, expect, test } from "bun:test"
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { buildHookRuleTransitionCandidate } from "../src/hook-rule-transition-candidate"
import type { Playbook, PlaybookBullet } from "../src/harness-store"

let storeRoot: string

function bullet(n: number, mode: "shadow" | "warn" | "deny" = "shadow"): PlaybookBullet {
  return {
    id: `b${n}`,
    text: `rule ${n}`,
    helpful: 0,
    harmful: 0,
    addedBy: "test",
    status: "active",
    createdAt: "2026-08-15T00:00:00.000Z",
    updatedAt: "2026-08-15T00:00:00.000Z",
    hookRule: { event: "PreToolUse", toolMatcher: "Bash", inputPattern: `^docker rule${n} `, feedback: `f${n}`, mode },
  }
}

function writeActive(pb: Playbook, tools = ""): void {
  const active = join(storeRoot, "active")
  mkdirSync(active, { recursive: true })
  writeFileSync(join(active, "playbook.json"), JSON.stringify(pb))
  if (tools) writeFileSync(join(active, "tools.md"), tools)
}

function candidatePlaybook(version: string): Playbook {
  return JSON.parse(readFileSync(join(storeRoot, "candidates", version, "playbook.json"), "utf-8"))
}

beforeEach(() => {
  storeRoot = mkdtempSync(join(tmpdir(), "hr-transition-store-"))
})
afterEach(() => {
  rmSync(storeRoot, { recursive: true, force: true })
})

test("happy path: builds a candidate whose playbook differs from active by EXACTLY the one mode field", () => {
  const pb: Playbook = { schemaVersion: 1, nextId: 3, bullets: [bullet(1, "warn"), bullet(2, "shadow")] }
  writeActive(pb, "TOOLS TEXT")
  const res = buildHookRuleTransitionCandidate(storeRoot, "b1")
  if ("error" in res) throw new Error(`unexpected refusal: ${res.error}`)
  expect(res.version).toBe("v1")

  const got = candidatePlaybook("v1")
  expect(got.bullets.find((b) => b.id === "b1")!.hookRule!.mode).toBe("deny")
  // Byte-diff discipline: flipping the one field back reproduces active exactly.
  got.bullets.find((b) => b.id === "b1")!.hookRule!.mode = "warn"
  expect(got).toEqual(pb)
  // system.md rendered + tools carried from active.
  expect(existsSync(join(storeRoot, "candidates", "v1", "system.md"))).toBe(true)
  expect(readFileSync(join(storeRoot, "candidates", "v1", "tools.md"), "utf-8")).toBe("TOOLS TEXT")
})

test("meta.json carries the transition provenance marker", () => {
  writeActive({ schemaVersion: 1, nextId: 2, bullets: [bullet(1, "warn")] })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b1")
  if ("error" in res) throw new Error(res.error)
  const meta = JSON.parse(readFileSync(join(storeRoot, "candidates", res.version, "meta.json"), "utf-8"))
  expect(meta.transition).toEqual({ bulletId: "b1", from: "warn", to: "deny" })
})

test("refuses a bullet whose hookRule mode is not warn", () => {
  writeActive({ schemaVersion: 1, nextId: 2, bullets: [bullet(1, "shadow")] })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b1")
  expect("error" in res && res.error).toContain("warn")
  expect(existsSync(join(storeRoot, "candidates"))).toBe(false)
})

test("refuses a missing / pruned / hookRule-less bullet", () => {
  const pruned = { ...bullet(2, "warn"), status: "pruned" as const }
  const noRule = { ...bullet(3, "warn"), hookRule: undefined }
  writeActive({ schemaVersion: 1, nextId: 4, bullets: [pruned, noRule] })
  for (const id of ["b1", "b2", "b3"]) {
    const res = buildHookRuleTransitionCandidate(storeRoot, id)
    expect("error" in res).toBe(true)
  }
  expect(existsSync(join(storeRoot, "candidates"))).toBe(false)
})

test("deny-cap pre-check: refuses when 4 deny rules are already exportable", () => {
  writeActive({
    schemaVersion: 1,
    nextId: 7,
    bullets: [bullet(1, "deny"), bullet(2, "deny"), bullet(3, "deny"), bullet(4, "deny"), bullet(5, "warn")],
  })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b5")
  expect("error" in res && res.error).toContain("deny")
  expect(existsSync(join(storeRoot, "candidates"))).toBe(false)
})

test("deny-cap counts EXPORTABLE deny rules only — a pruned deny bullet does not block", () => {
  const prunedDeny = { ...bullet(4, "deny"), status: "pruned" as const }
  writeActive({
    schemaVersion: 1,
    nextId: 7,
    bullets: [bullet(1, "deny"), bullet(2, "deny"), bullet(3, "deny"), prunedDeny, bullet(5, "warn")],
  })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b5")
  expect("error" in res).toBe(false)
})

test("version numbering follows the store convention (next free vN)", () => {
  writeActive({ schemaVersion: 1, nextId: 2, bullets: [bullet(1, "warn")] })
  mkdirSync(join(storeRoot, "candidates", "v0"), { recursive: true })
  mkdirSync(join(storeRoot, "candidates", "v3"), { recursive: true })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b1")
  if ("error" in res) throw new Error(res.error)
  expect(res.version).toBe("v4")
})

test("system-generated by construction: module never imports review-gate, and no rejected ledger appears", () => {
  const src = readFileSync(join(import.meta.dir, "..", "src", "hook-rule-transition-candidate.ts"), "utf-8")
  expect(src).not.toContain("review-gate")
  writeActive({ schemaVersion: 1, nextId: 2, bullets: [bullet(1, "warn")] })
  const res = buildHookRuleTransitionCandidate(storeRoot, "b1")
  if ("error" in res) throw new Error(res.error)
  expect(existsSync(join(storeRoot, "rejected.json"))).toBe(false)
})
