/**
 * hook-rule-transition-candidate.ts — system-generated warn→deny candidate
 * constructor (hook-rule P3 plan, T5; spec §4). warn→deny is NEVER automatic:
 * this builds an INACTIVE candidate whose playbook differs from active by
 * exactly one field (the target bullet's hookRule.mode), for the ab gate to
 * measure like any candidate — running that arm is P4 (explicit go + spend).
 *
 * System-generated by construction: the candidate never passes through the
 * propose/review pipeline — the `transition` provenance field in meta.json is
 * the marker. Deny-cap pre-check simulates the FLIPPED playbook through the
 * exporter's own compileHookRulesTable, so a candidate whose deny rule the
 * table would truncate (spec §4: "an arm the table would truncate is never
 * built") is refused up front rather than silently measured as a no-op.
 */
import {
  createCandidate,
  nextVersion,
  readActiveTools,
  readPlaybook,
  renderPlaybook,
  writeCandidateMeta,
  type Playbook,
} from "./harness-store.ts"
import { compileHookRulesTable } from "./hook-rules-export.ts"

export function buildHookRuleTransitionCandidate(
  storeRoot: string,
  bulletId: string,
): { version: string } | { error: string } {
  const active = readPlaybook(storeRoot)
  if (!active) return { error: "no active playbook" }

  const target = active.bullets.find((b) => b.id === bulletId)
  if (!target || target.status !== "active") return { error: `bullet ${bulletId} not found or not active` }
  if (!target.hookRule) return { error: `bullet ${bulletId} carries no hookRule` }
  if (target.hookRule.mode !== "warn")
    return { error: `bullet ${bulletId} mode is "${target.hookRule.mode}", not "warn" — transition candidates are warn→deny only` }

  // Copy with ONLY the target mode flipped.
  const flipped: Playbook = {
    ...active,
    bullets: active.bullets.map((b) =>
      b.id === bulletId ? { ...b, hookRule: { ...b.hookRule!, mode: "deny" as const } } : b,
    ),
  }

  // Deny-cap pre-check against the flipped table: the bullet must survive
  // compilation WITH mode deny, or the arm would measure a truncated no-op.
  const { rules } = compileHookRulesTable(flipped)
  const compiled = rules.find((r) => r.id === bulletId)
  if (!compiled || compiled.mode !== "deny")
    return { error: `flip would exceed the deny cap (or be truncated) — ${bulletId} not exportable as deny` }

  const version = nextVersion(storeRoot)
  createCandidate(storeRoot, version, renderPlaybook(flipped), readActiveTools(storeRoot), flipped)
  writeCandidateMeta(storeRoot, version, {
    transition: { bulletId, from: "warn", to: "deny" },
  })
  return { version }
}
